### ISSUE TITLE
what is scale_train in dropout layer?

### ISSUE THREAD

**Issue by jwyang** [ShaoqingRen/faster_rcnn#14]
Dear Shaoqing, 

I am wondering what is the acutal meanning for scale_train in your dropout layer. I cannot find such parameter in original Caffe project. 

Because i encountered an unknown error when runing your caffe_.mexw64, i have to use my own, but it is not compatible to your prototxt file. 

What do you think is the best solution to my issue?

Thanks,

**Comment by ShaoqingRen** [comment]
Hi jwyang,

scale_train = true is what offical Caffe doing, scale_train  = false, is making the scale operation in testing phase instead of training phase. Please read our code, the difference is obvious. 

If you have problem in running the downloaded caffe_.mexw64, please compile one with our modifided Caffe.

**Comment by jwyang** [comment]
thanks, shaoqing, i wil read the codes in your modified Caffe, and compile it for usage.
