### ISSUE TITLE
Is the windows version only support CUDA 6.5 ?

### ISSUE THREAD

**Issue by shiorioxy** [ShaoqingRen/faster_rcnn#56]
When I run the script in cuda 7.0, I meet a error.

fast_rcnn startup done
GPU 1: free memory 7093714944
Use GPU 1
Invalid MEX-file 'D:\faster_rcnn-master\external\caffe\matlab\caffe_faster_rcnn\caffe_.mexw64': 找不到指定的模块。

Error in caffe.set_device (line 9)
caffe_('set_device', device_id);

Error in active_caffe_mex (line 26)
    caffe.set_device(gpu_id-1);

Error in script_faster_rcnn_demo (line 10)
active_caffe_mex(opts.gpu_id, opts.caffe_version);

**Comment by Anylee2142** [comment]
before i answer your question, 

would you mind to tell me your gpu?

**Comment by Anylee2142** [comment]
well i met the same problem as yours.

simply changing to 6.5 solved my invalid MEX file error.

But when i runned Testing demo, i got the error below.
--------------------------------------------------------------------------------------------
Error using caffe_
glog check error, please check log and clear mex

Error in caffe.Net/forward_prefilled (line 109)
      caffe_('net_forward', self.hNet_self);

Error in caffe.Net/forward (line 142)
      self.forward_prefilled();

Error in proposal_im_detect (line 23)
    output_blobs = caffe_net.forward(net_inputs);

Error in script_faster_rcnn_demo (line 54)
    [boxes, scores]             =
    proposal_im_detect(proposal_detection_model.conf_proposal, rpn_net, im);
--------------------------------------------------------------------------------------------

and generated log file says that 

F0108 15:05:29.329790 10104 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
F0108 15:05:29.329790 10104 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

i'm not sure whether 'out of memory' indicates gpu or cpu
 
but i guess it's because of my gpu. gtx titan 650 ti.

if you solve your error and become able to test demo properly, 
would you mind if i ask what your gpu is?
please let me know.

**Comment by Anylee2142** [comment]
well i met the same problem as yours.

simply changing to 6.5 solved my invalid MEX file error.

But when i runned Testing demo, i got the error below.
--------------------------------------------------------------------------------------------
Error using caffe_
glog check error, please check log and clear mex

Error in caffe.Net/forward_prefilled (line 109)
      caffe_('net_forward', self.hNet_self);

Error in caffe.Net/forward (line 142)
      self.forward_prefilled();

Error in proposal_im_detect (line 23)
    output_blobs = caffe_net.forward(net_inputs);

Error in script_faster_rcnn_demo (line 54)
    [boxes, scores]             =
    proposal_im_detect(proposal_detection_model.conf_proposal, rpn_net, im);
--------------------------------------------------------------------------------------------

and generated log file says that 

F0108 15:05:29.329790 10104 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
F0108 15:05:29.329790 10104 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

i'm not sure whether 'out of memory' indicates gpu or cpu
 
but i guess it's because of my gpu. gtx titan 650 ti.

if you solve your error and become able to test demo properly, 
would you mind if i ask what your gpu is?
please let me know.

**Comment by shiorioxy** [comment]
My GPU is 980M.
I fixed this question. It is ture, the error is related to the CUDA version.
I change 7.0 to 6.5, everything is OK!
I close this issus.
